<?xml version="1.0" encoding="UTF-8"?>



<!-- prolog/xml declaartion -->
<!-- DTD -->
<!DOCTYPE PRODUCT
[
<!ELEMENT PRODUCT (PRODUCTKANAME,PRODUCTPRICE,PRODUCTMETRIAL,SHOPADDRESS,CONTACTNUMBER)>
<!ELEMENT PRODUCTKANAME (#PCDATA)>
<!ELEMENT PRODUCTPRICE (ONELODU,KGLODU)>
<!ELEMENT ONELODU (#PCDATA)>
<!ELEMENT KGLODU (#PCDATA)>
<!ELEMENT PRODUCTMETRIAL (#PCDATA)>
<!ELEMENT SHOPADDRESS (VILLAGE,AREA,SHOPNO)>
<!ELEMENT VILLAGE (#PCDATA)>
<!ELEMENT AREA (#PCDATA)>
<!ELEMENT SHOPNO (#PCDATA)>
<!ELEMENT CONTACTNUMBER (EMAIL,PHONENUMBER,FACEBOOK)>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT PHONENUMBER (#PCDATA)>
<!ELEMENT FACEBOOK (#PCDATA)>












]>



<!-- body/data -->
<!-- namespace -->
<PRODUCT>
<PRODUCTKANAME>
    TUNTUNMOSI KLADU
</PRODUCTKANAME>
<PRODUCTPRICE>
    <ONELODU>500</ONELODU>
    <KGLODU>5000</KGLODU>
</PRODUCTPRICE>
<PRODUCTMETRIAL>
 BESHAN K cLADU
</PRODUCTMETRIAL>
<SHOPADDRESS>
    <VILLAGE>
        DHOLAKPUR
    </VILLAGE>
    <AREA>
        CHUTKI KA GHER
    </AREA>
    <SHOPNO>
        420 
    </SHOPNO>
</SHOPADDRESS>
<CONTACTNUMBER>
    <EMAIL>
        ZOHAIBMOOSANI184@GMAIL.COM
    </EMAIL>
    <PHONENUMBER>
        03421976526
    </PHONENUMBER>
    <FACEBOOK>
        DHOLAKPUR K MASHOOR LADU
    </FACEBOOK>
</CONTACTNUMBER>
</PRODUCT>